version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=post"
      - "POSTGRES_DB=postgres"
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
